-- 코드를 입력하세요
SELECT
    PRODUCT_CODE,
    SUM(PRICE * SALES_AMOUNT) AS SALES
FROM
    PRODUCT
        INNER JOIN OFFLINE_SALE
                   ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY
    PRODUCT_CODE
ORDER BY
    SALES DESC,
    PRODUCT_CODE


-- 코드를 입력하세요
SELECT
    ai.ANIMAL_ID, ai.NAME
FROM
    ANIMAL_INS ai
        INNER JOIN ANIMAL_OUTS ao
                   ON ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE
    ai.DATETIME > ao.DATETIME
ORDER BY
    ai.DATETIME


-- 코드를 입력하세요
SELECT
    ao.ANIMAL_ID,
    ao.NAME
FROM
    ANIMAL_INS ai INNER JOIN
    ANIMAL_OUTS ao
    ON ai.ANIMAL_ID = ao.ANIMAL_ID
ORDER BY
    ( ao.DATETIME - ai.DATETIME ) DESC
    LIMIT 2


-- 코드를 입력하세요
SELECT
    BOOK_ID,
    AUTHOR_NAME,
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM
    BOOK b INNER JOIN
    AUTHOR a
    ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE
    CATEGORY = '경제'
ORDER BY
    PUBLISHED_DATE