조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기
SELECT
    CONCAT('/home/grep/src/', ugf.BOARD_ID, '/', ugf.FILE_ID, ugf.FILE_NAME,  ugf.FILE_EXT) AS FILE_PATH
FROM
    USED_GOODS_FILE ugf
        JOIN
    USED_GOODS_BOARD ugb ON ugf.BOARD_ID = ugb.BOARD_ID
WHERE
        ugb.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY
    ugf.FILE_ID DESC;

저자 별 카테고리 별 매출액 집계하기
SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM
    BOOK B
        JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
        JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE
        EXTRACT(YEAR FROM BS.SALES_DATE) = 2022 AND EXTRACT(MONTH FROM BS.SALES_DATE) = 1
GROUP BY
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY
    A.AUTHOR_ID ASC,
    B.CATEGORY DESC;
주문량이 많은 아이스크림들 조회하기
SELECT FLAVOR
FROM (
         SELECT
             FLAVOR,
             SUM(TOTAL_ORDER) AS TOTAL
         FROM (
                  SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
                  UNION ALL
                  SELECT FLAVOR, TOTAL_ORDER FROM JULY
              ) AS T
         GROUP BY FLAVOR
         ORDER BY TOTAL DESC
     ) AS T
LIMIT 3;

대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
SELECT DATE_FORMAT(START_DATE, '%m') AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
    )
  AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY DATE_FORMAT(START_DATE, '%m'), CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH ASC, CAR_ID DESC;
