그룹별 조건에 맞는 식당 목록 출력하기
SELECT
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    MEMBER_PROFILE MP
        JOIN
    REST_REVIEW RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE
        MP.MEMBER_ID = (
        SELECT
            MEMBER_ID
        FROM
            (SELECT
                 MEMBER_ID,
                 COUNT(*) AS REVIEW_COUNT
             FROM
                 REST_REVIEW
             GROUP BY
                 MEMBER_ID
             ORDER BY
                 REVIEW_COUNT DESC
             LIMIT 1) TEMP)
ORDER BY
    RR.REVIEW_DATE,
    RR.REVIEW_TEXT;

오프라인/온라인 판매 데이터 통합하기
SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM
    (SELECT
         SALES_DATE,
         PRODUCT_ID,
         USER_ID,
         SALES_AMOUNT
     FROM
         ONLINE_SALE
     WHERE
             DATE_FORMAT(SALES_DATE, '%Y%m') = '202203'

     UNION ALL

     SELECT
         SALES_DATE,
         PRODUCT_ID,
         NULL AS USER_ID,
         SALES_AMOUNT
     FROM
         OFFLINE_SALE
     WHERE
             DATE_FORMAT(SALES_DATE, '%Y%m') = '202203') AS TOTAL_SALES
ORDER BY
    SALES_DATE,
    PRODUCT_ID,
    USER_ID;

조건에 부합하는 중고거래 댓글 조회하기
SELECT
    B.TITLE,
    B.BOARD_ID,
    R.REPLY_ID,
    R.WRITER_ID,
    R.CONTENTS,
    DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM
    USED_GOODS_BOARD B
        INNER JOIN
    USED_GOODS_REPLY R
    ON
            B.BOARD_ID = R.BOARD_ID
WHERE
        YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10
ORDER BY
    R.CREATED_DATE ASC,
    B.TITLE ASC;

입양 시각 구하기(2)
SELECT
    TIME.HOUR,
    COUNT(ANIMAL_OUTS.DATETIME) AS COUNT
FROM
    (SELECT 0 AS HOUR
     UNION ALL SELECT 1
     UNION ALL SELECT 2
     UNION ALL SELECT 3
     UNION ALL SELECT 4
     UNION ALL SELECT 5
     UNION ALL SELECT 6
     UNION ALL SELECT 7
     UNION ALL SELECT 8
     UNION ALL SELECT 9
     UNION ALL SELECT 10
     UNION ALL SELECT 11
     UNION ALL SELECT 12
     UNION ALL SELECT 13
     UNION ALL SELECT 14
     UNION ALL SELECT 15
     UNION ALL SELECT 16
     UNION ALL SELECT 17
     UNION ALL SELECT 18
     UNION ALL SELECT 19
     UNION ALL SELECT 20
     UNION ALL SELECT 21
     UNION ALL SELECT 22
     UNION ALL SELECT 23) AS TIME
        LEFT JOIN
    ANIMAL_OUTS
    ON
            TIME.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY
    TIME.HOUR
ORDER BY
    TIME.HOUR;
