대여 기록이 존재하는 자동차 리스트 구하기
SELECT DISTINCT CAR_RENTAL_COMPANY_CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR
         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ON CAR_RENTAL_COMPANY_CAR.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
WHERE CAR_RENTAL_COMPANY_CAR.CAR_TYPE = '세단'
  AND MONTH(CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE) = 10
ORDER BY CAR_RENTAL_COMPANY_CAR.CAR_ID DESC;

식품분류별 가장 비싼 식품의 정보 조회하기
SELECT
    CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM
    (
        SELECT
            CATEGORY,
            PRICE,
            PRODUCT_NAME,
            RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK
        FROM
            FOOD_PRODUCT
        WHERE
                CATEGORY IN ('과자', '국', '김치', '식용유')
    ) FP
WHERE
        PRICE_RANK = 1
ORDER BY
    MAX_PRICE DESC;

즐겨찾기가 가장 많은 식당 정보 출력하기
SELECT
    FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM
    (
        SELECT
            FOOD_TYPE,
            REST_ID,
            REST_NAME,
            FAVORITES,
            RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS FAVORITES_RANK
        FROM
            REST_INFO
    ) RI
WHERE
        FAVORITES_RANK = 1
ORDER BY
    FOOD_TYPE DESC;
5월 식품들의 총매출 조회하기
SELECT
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME,
    SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_SALES
FROM
    FOOD_PRODUCT FP
        JOIN
    FOOD_ORDER FO
    ON
            FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE
        DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC,
    FP.PRODUCT_ID ASC;