이름이 없는 동물의 아이디
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY ANIMAL_ID ASC;

조건에 맞는 회원수 구하기
SELECT COUNT(*) AS 회원수
FROM USER_INFO
WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
  AND AGE BETWEEN 20 AND 29;

카테고리 별 상품 개수 구하기
SELECT SUBSTRING(PRODUCT_CODE, 1, 2) AS 카테고리_코드, COUNT(*) AS 상품_개수
FROM PRODUCT
GROUP BY SUBSTRING(PRODUCT_CODE, 1, 2)
ORDER BY SUBSTRING(PRODUCT_CODE, 1, 2) ASC;

중성화 여부 파악하기
SELECT ANIMAL_ID, NAME,
       CASE
           WHEN SEX_UPON_INTAKE LIKE '%Neutered%' OR SEX_UPON_INTAKE LIKE '%Spayed%' THEN 'O'
           ELSE 'X'
           END AS 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;
