// 아픈 동물 찾기

SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'
ORDER BY ANIMAL_ID;

//중복 제거 하기

SELECT COUNT(DISTINCT NAME) AS TotalNames
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;

