// 여러 기준으로 정렬하기
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC;


// 동물 수 구하기
SELECT COUNT(*) AS count
FROM ANIMAL_INS;

//최솟값 구하기
SELECT MIN(DATETIME) AS 시간
FROM ANIMAL_INS;

// 이름이 있는 동물의 아이디
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID;
