// 이름이 없는 동물의 아이디

SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY ANIMAL_ID ASC;

// 조건에 맞는 회원수 구하기

SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE YEAR(JOINED) = 2021
AND AGE BETWEEN 20 AND 29;

// 중성화 여부 파악하기

SELECT ANIMAL_ID, NAME, (
        CASE
            WHEN SEX_UPON_INTAKE LIKE 'Neutered%' THEN 'O'
            WHEN SEX_UPON_INTAKE LIKE 'Spayed%' THEN 'O'
            ELSE 'X'
            END
        ) AS '중성화'
FROM ANIMAL_INS

// 카테고리 별 상품 개수 구하기

SELECT LEFT(PRODUCT_CODE, 2) AS 'CATEGORY', COUNT(PRODUCT_ID) AS 'PRODUCTS'
FROM PRODUCT GROUP BY LEFT(PRODUCT_CODE, 2)
ORDER BY CATEGORY