-- 상품 별 오프라인 매출 구하기
SELECT PRODUCT_CODE,
       SUM(SALES_AMOUNT) * P.PRICE AS SALES
FROM PRODUCT P
         INNER JOIN OFFLINE_SALE OS ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;