// 이름이 없는 동물의 아이디
SELECT
    ANIMAL_ID
FROM
    ANIMAL_INS
WHERE
    NAME IS NULL
ORDER BY
    ANIMAL_ID ASC;

// 조건에 맞는 회원수 구하기
SELECT
    COUNT(*) AS USERS
FROM
    USER_INFO
WHERE
    YEAR(JOINED) = 2021
    AND
    AGE BETWEEN 20 AND 29;

// 카테고리 별 상품 개수 구하기
SELECT
  ANIMAL_ID,
  NAME,
  CASE
    WHEN SEX_UPON_INTAKE LIKE 'Neutered%' THEN 'O'
    WHEN SEX_UPON_INTAKE LIKE 'Spayed%' THEN 'O'
    ELSE 'X'
  END SEX_UPON_INTAKE
FROM ANIMAL_INS

// 경기도에 위치한 식품창고 목록 출력하기
SELECT 
    WAREHOUSE_ID, 
    WAREHOUSE_NAME, 
    ADDRESS,
    CASE
        WHEN FREEZER_YN IS NULL THEN 'N'
        ELSE FREEZER_YN
    END FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기도%'
ORDER BY WAREHOUSE_ID ASC;
